"""empty message

Revision ID: b86eb09e9558
Revises: bd77eb9e68d7
Create Date: 2022-08-31 10:24:05.445933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b86eb09e9558'
down_revision = 'bd77eb9e68d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=100), nullable=True))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=200), nullable=True))
    op.drop_column('user', 'email')
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###
